name: Auto Merge Dependabot Pull Requests

on:
  workflow_call:

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          # Custom GITHUB_TOKEN is required in order to successfully merge dependabot
          # pull requests when integrate workflow is green.
          GITHUB_TOKEN: ${{ secrets.MERGE_ME_GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
