name: MySQL Backup Restore

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Name of your application'
        required: true
        type: string
      database_name:
        description: 'Name of the database to be created'
        required: true
        type: string
      php_version:
        description: 'PHP version to be used.'
        required: true
        type: string
        default: '8.4'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS ACCESS KEY to download your backup'
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS SECRET ACCESS KEY to download your backup'
      AWS_DEFAULT_REGION:
        required: true
        description: 'AWS region your backup is located'
      AWS_BACKUP_BUCKET:
        required: true
        description: 'Name of the AWS S3 bucket your backup is stored in.'
      BACKUP_ARCHIVE_PASSWORD:
        required: true
        description: 'The password used to decrypt your backup.'

jobs:
  backuip-restore:
    name: MySQL Backup Restore
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ${{ inputs.database_name }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}

      - run: cp .env.example .env

      - uses: ramsey/composer-install@v2

      - run: php artisan key:generate

      - name: Restore Backup
        run: php artisan backup:restore --backup=latest --no-interaction
        env:
            APP_NAME: ${{ inputs.app_name }}
            DB_PASSWORD: 'password'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_BACKUP_BUCKET: ${{ secrets.AWS_BACKUP_BUCKET }}
            BACKUP_ARCHIVE_PASSWORD: ${{ secrets.BACKUP_ARCHIVE_PASSWORD }}

      - name: Wipe Database
        run: php artisan db:wipe --no-interaction
        env:
            DB_PASSWORD: 'password'
