name: "Integrate"

on:
  workflow_call:
    secrets:
      COMPOSER_GITHUB_TOKEN:
        required: true
        description: 'GitHub Token used to install private composer packages.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl

      - name: Setup composer auth.json
        run: composer config github-oauth.github.com ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - uses: ramsey/composer-install@v2

      - name: Create new Jigsaw Build
        run: composer run build:production
