name: "Integrate"

on:
  workflow_call:

jobs:
  frontend-build:
    if: github.actor == 'dependabot[bot]'
    name: Frontend Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies
        run: yarn install

      - name: Build Frontend Assets
        run: yarn prod
