name: "Integrate"

on:
  workflow_call:
    secrets:
      COMPOSER_GITHUB_TOKEN:
        required: true
        description: 'GitHub Token used to install private composer packages.'
    inputs:
      phpVersion:
        description: 'Version of PHP to be used'
        required: false
        type: string
        default: '8.4'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl

      - name: Setup composer auth.json
        run: composer config github-oauth.github.com ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - uses: ramsey/composer-install@v2

      - name: Create new Jigsaw Build
        run: composer run build:production
