name: On Demand Build

on:
  workflow_call:
    inputs:
      commit_message:
        description: 'Commit Message used for this new build.'
        required: false
        type: string
        default: 'New On Demand Build'
      phpVersion:
        description: 'Version of PHP to be used'
        required: false
        type: string
        default: '8.2'
    secrets:
      COMPOSER_GITHUB_TOKEN:
        required: true
        description: 'GitHub Token used to install private composer packages.'

jobs:
  build:
    name: On Demand Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl

      - name: Setup composer auth.json
        run: composer config github-oauth.github.com ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - uses: ramsey/composer-install@v2

      - name: Create new Jigsaw Build
        run: vendor/bin/jigsaw build production

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit_message }}
          branch: main
